spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/social_network_db
    username: root
    password: root

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://networkinstance.crq9k6hmt4ul.eu-central-1.rds.amazonaws.com:3306/network_db
    username: admin
    password: 070809az