spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/social_network_db
    username: root
    password: root

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://social_network_mysql/social_network_db
    username: root
    password: 070809az