spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/social_network_db
    username: root
    password: root

com:
  practice:
    social_network:
      jwt:
        jwtSecret: c3VwZXJTZWNyZXRLZXk=
        jwtExpirationMinutes: 60
        refreshTokenExpirationMinutes: 180

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://social_network_mysql/social_network_db
    username: root
    password: 070809az

com:
  practice:
    social_network:
      jwt:
        jwtSecret: c3VwZXJTZWNyZXRLZXk=
        jwtExpirationMinutes: 60
        refreshTokenExpirationMinutes: 180