ALTER TABLE followings
    ADD COLUMN archived TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE posts
    ADD COLUMN archived TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE posts_comments
    ADD COLUMN archived TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE posts_likes
    ADD COLUMN archived TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE users
    ADD COLUMN archived TINYINT(1) NOT NULL DEFAULT 0;
